language: cpp
compiler:
- gcc
script:
- cmake . && make && ARGS=-V make test
# TODO ./tests/integration.sh
sudo: required
before_install:
- sudo apt-get install build-essential clang liblog4cxx10-dev libboost-all-dev txt2man php-pear php-all-dev libcurl4-openssl-dev
- sudo apt-get install libgearman-dev gearman-job-server gearman libgearman7
# TODO install PHP gearman extension
