language: cpp
compiler:
- gcc
script:
- cmake . && make driveshaft_unit_tests && make test
- make driveshaft && ./tests/integration.sh
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
sudo: required
before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -qq
- sudo apt-get install -qq build-essential gcc-4.8 g++-4.8 clang libgearman-dev liblog4cxx10-dev libboost-all-dev gearman-job-server libcurl4-openssl-dev gearman-dev php-pear php5-dev
- sudo pecl install gearman
